### ISSUE TITLE
Error in Doorbird communication

### ISSUE THREAD

**Issue by Quido78** [ihrigb/node-red-contrib-doorbird-ultimate#30] opened 2024-04-18 11:30 UTC
Hello, 

I would like to kindly ask you for help with Receiving „Error in Doorbird communication.“ 

Node-Red, version: 3.0.2.
Running on: Raspberry Pi 3, Debian, version: 10
Node: node-red-contrib-doorbird-ultimate, version: 1.4.0

 What is working:
- Ring – when ring button is pressed, I fot the message to Google Nest Mini 2 and selected lights are blinking

What is not working:
- Info node: msg : string[32] Error in Doorbird communication
- Video node and Image node set to Dashboard: no picture, no video on dashboard, just empty frame

What has been checked/tested:
- new user and password set for Doorbird is ok (otherwise Ring will not work)
- permissions in Doorbird App are set to all, except Door Open (own security)
- In Node-Red, testing node UDP In with port set to 6524 is sending to debug node payload buffer [22] with message [ 54, 50, 56, 55, 58, 103, 103, 122, 122, 106 …] (I have seen it in another post here, so I set it up for test as well)
- I've also played with Router Firewall, but nothing helped

**Comment by ihrigb** [comment] 2024-04-18 13:51
Thanks for the detailed report. I will try to look into it as soon as possible. Can you check the server logs for anything that hints to the root cause?

**Comment by Quido78** [comment] 2024-04-18 14:31
How to get server logs? I do have device like this: https://help.ampio.com/en/modules/m-serv-s/

And it is running also Node-Red on it. I can login to device as root via Putty, but do not know which logs are you looking for .

 

Best regards, 

Quido Květ

 ***@***.***> ***@***.***

**Comment by ihrigb** [comment] 2024-05-09 21:37
@Quido78 sorry for the delay. I did finally have a bit of time to look into this. I cannot identify an issue that would prevent any normal call to the API (for example info). All of them do work for me.
I do not know your device and thus I do not know, how to access node red logs.

**Comment by ihrigb** [comment] 2024-09-16 19:08
Closing this as idle.

**Closed by ihrigb** 2024-09-16 19:08 UTC
Labels: bug
